weather/proj/automaticas/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

weather/proj/normais/urls.py
from django.conf.urls import url
from django.contrib import admin

from normais import views
from djgeojson.views import GeoJSONLayerView
from normais.models import Station, FocoItem

urlpatterns = [    
    url(r'^$', views.normais ),
    url(r'^accounts/login/$', views.loginusr ),
    url(r'^sair/$', views.sair ),
    url(r'^normais/$', views.normais ),
    url(r'^automaticas/$', views.automaticas ),
    url(r'^grafnormais/(?P<station>\d+)/(?P<texto>[\w ]+)/$', views.grafnormais ),
    url(r'^grafautomatica/(?P<station>\d+)/(?P<mes>\d+)/(?P<ano>\d+)/(?P<texto>[\w ]+)/$', views.grafAutomatica ),
    url(r'^getautomaticajson/(?P<station>\d+)/$', views.getautomaticajson),
    url(r'^grafautomaticatotal/(?P<station>\d+)/(?P<texto>[\w ]+)/$', views.grafAutomaticaTotal),
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model= Station, properties=('id', 'Altitude', 'Codigo', 'Nome','Estado',"tipo",'tipo',)), name='data'),
    url(r'^fire.geojson$', GeoJSONLayerView.as_view(model= FocoItem), name='data'),
    url(r'^mapaestacoes/$', views.mapaestacoes),
    url(r'^mapafocoincendio/$', views.mapafocoincendio),
    url(r'^focoCalor/(?P<id>\d+)/$', views.focoCalor),
]

weather/proj/proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.site.site_header = u'SIMOF - Terravision'

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('normais.urls')),
    url(r'^', include('projetos.urls')),
    url(r'^', include('igam.urls')),
    url(r'^', include('monitor.urls')),
    url(r'^', include('roi.urls')),
]

weather/proj/roi/urls.py
# -*- coding: utf-8 -*- 
#!/usr/bin/env python 

from django.conf.urls import url
from django.contrib import admin
from roi import views

urlpatterns = [    
    url(r'^DetailROI/(?P<idRoi>\d+)/$', views.DetailROI),
]

weather/proj/automaticas/models.py
# -*- coding: utf-8 -*- 
#!/usr/bin/env python 

from django.db import models
from normais.models import Station

weather/proj/normais/models.py
# -*- coding: utf-8 -*- 
#!/usr/bin/env python 

#from django.db import models
from django.contrib.gis.db import models
from paintstore.fields import ColorPickerField
# Create your models. here.

class Station(models.Model):
    tipo = models.CharField(max_length=1, default='N')
    Codigo = models.CharField(max_length=6)
    Nome = models.CharField(max_length=100)
    Estado = models.CharField(max_length=50)
    UF = models.CharField(max_length=2)
    Altitude = models.DecimalField(default=0, decimal_places=2, max_digits=16) 
    LatLong = models.CharField(max_length=100)
    posicao = models.PointField()

    objects = models.GeoManager()

    @property
    def geom(self):
        return self.posicao

    class Meta:
        ordering = ['Nome',]     

    def __unicode__(self):              
        return u'{0}'.format(self.Nome) 

class Foco(models.Model):

    dataUTC     = models.DateTimeField()
    dataregUTC  = models.DateTimeField()
    arquivo     = models.CharField(max_length=100)
    
    class Meta:
        ordering = ['dataUTC',]     

    def __unicode__(self):              
        return u'{0}'.format(self.dataUTC) 

class FocoItem(models.Model):

    foco_FK     = models.ForeignKey(Foco, verbose_name="Foco" )
    posicao     = models.PointField()
    Satzen      = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    PixSize     = models.DecimalField(default=0, decimal_places=4, max_digits=16)
    T4          = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    T11         = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    FireSize    = models.DecimalField(default=0, decimal_places=4, max_digits=16)
    Temp        = models.IntegerField(default=0)
    FRP         = models.IntegerField(default=0)
    Ecosystem   = models.IntegerField(default=0)
    FireFlag    = models.IntegerField(default=0)
    objects = models.GeoManager()

    @property
    def geom(self):
        return self.posicao

    def __unicode__(self):              
        return u'{0}'.format(self.T4) 



class Classe(models.Model):
    Nome = models.CharField(max_length=100)

    def __unicode__(self):              
        return u'{0}'.format(self.Nome) 

class Parametro(models.Model):
    codigo =  models.IntegerField(default=0)
    Nome = models.CharField(max_length=100)
    Classe_FK = models.ForeignKey(Classe, null=True, blank=True, default = None, verbose_name="Classe" )
    Planilha = models.CharField(max_length=200, default='')
    jan = models.IntegerField(default=0)
    fev = models.IntegerField(default=0)
    mar = models.IntegerField(default=0)
    abr = models.IntegerField(default=0)
    mai = models.IntegerField(default=0)
    jun = models.IntegerField(default=0)
    jul = models.IntegerField(default=0)
    ago = models.IntegerField(default=0)
    stb = models.IntegerField(default=0)
    out = models.IntegerField(default=0)
    nov = models.IntegerField(default=0)
    dez = models.IntegerField(default=0)
    tot = models.IntegerField(default=0)
    unidade = models.CharField(max_length=15, blank=True, default = '')
    corGrafico = ColorPickerField(help_text="Clique no campo para abrir o colorpicker.", max_length=7)

    class Meta:
        ordering = ['Nome',]

    def __unicode__(self):              
        return u'{0}'.format(self.Nome) 

class ResultStr(models.Model):

    Station_FK  = models.ForeignKey(Station, verbose_name="Estação" )
    Parametro_FK  = models.ForeignKey(Parametro, verbose_name="Parâmetro" )
    jan = models.CharField(max_length=20, default='')
    fev = models.CharField(max_length=20, default='')
    mar = models.CharField(max_length=20, default='')
    abr = models.CharField(max_length=20, default='')
    mai = models.CharField(max_length=20, default='')
    jun = models.CharField(max_length=20, default='')
    jul = models.CharField(max_length=20, default='')
    ago = models.CharField(max_length=20, default='')
    stb = models.CharField(max_length=20, default='')
    out = models.CharField(max_length=20, default='')
    nov = models.CharField(max_length=20, default='')
    dez = models.CharField(max_length=20, default='')
    tot = models.CharField(max_length=20, default='')


    def __unicode__(self):              
        return u'{0}'.format(self.Parametro_FK) 

class Resultado(models.Model):

    Station_FK  = models.ForeignKey(Station, verbose_name="Estação" )
    Parametro_FK  = models.ForeignKey(Parametro, verbose_name="Parâmetro" )
    jan = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    fev = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    mar = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    abr = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    mai = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    jun = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    jul = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    ago = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    stb = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    out = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    nov = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    dez = models.DecimalField(default=0, decimal_places=2, max_digits=16)
    tot = models.DecimalField(default=0, decimal_places=2, max_digits=16)


    def __unicode__(self):              
        return u'{0}'.format(self.Parametro_FK) 

weather/proj/automaticas/forms.py
from django import forms

# place form definition here

weather/proj/normais/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python

from django import forms

class PesquisaEstacaoFRM(forms.Form):
    nomeEstacao  = forms.CharField(label='Estação', max_length=100)
    nomeTexto    = forms.CharField(label='Texto', max_length=100, initial='', required=False)

class PesquisaAutomaticasFRM(forms.Form):


    MES_CHOICES  = (
        ('99',  'Geral'),
        ('0',  'Anual'),
        ('1',  'Janeiro'),
        ('2',  'Fevereiro'),
        ('3',  'Março'),
        ('4',  'Abril'),
        ('5',  'Maio'),
        ('6',  'Junho'),
        ('7',  'Julho'),
        ('8',  'Agosto'),
        ('9',  'Setembro'),
        ('10', 'Outubro'),
        ('11', 'Novembro'),
        ('12', 'Dezembro'),
    )

    ANO_CHOICES  = (
        ('2000', '2000'),
        ('2001', '2001'),
        ('2002', '2002'),
        ('2003', '2003'),
        ('2004', '2004'),
        ('2005', '2005'),
        ('2006', '2006'),
        ('2007', '2007'),
        ('2008', '2008'),
        ('2009', '2009'),
        ('2010', '2010'),
        ('2011', '2011'),
        ('2012', '2012'),
        ('2013', '2013'),
        ('2014', '2014'),
        ('2015', '2015'),
        ('2016', '2016'),

    )



    nomeEstacao  = forms.CharField(label='Estação', max_length=100)
    ano          = forms.ChoiceField(choices=ANO_CHOICES)
    mes          = forms.ChoiceField(choices=MES_CHOICES)
    nomeTexto    = forms.CharField(label='Texto', max_length=100, initial='', required=False)

weather/proj/automaticas/views.py
# Create your views here.

weather/proj/normais/views.py
# -*- coding: utf-8 -*- 
#!/usr/bin/env python

from django.shortcuts import render, redirect
from django.http import HttpResponse
import models as db
from django.core import serializers
from django.template import RequestContext, loader
from forms import PesquisaEstacaoFRM, PesquisaAutomaticasFRM
from toolbox.tools import ObjectView

from normais.regras import NormalGraficos
from automaticas.graficos   import GeraGraficos
from automaticas.regras    import Medicao
from datetime import datetime
from django.utils import http
from django.shortcuts import  redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def loginusr(request):

    state = "Por favor informe seu usuario e senha..."
    username = password = ''
    
    template = loader.get_template('login.html')
    if request.POST:
        username = request.POST['usuario']
        password = request.POST['senha']
        
        user = authenticate(username=username, password=password)        
        if user is not None:
            if user.is_active:       
                login(request,user)                     
                return redirect('/dashboard/1/')                                           
            else:
                state = u"Sua conta esta desativada, por favor entre em contato com o administrador.."
        else:
            state = u"Seu usuario ou senha estao  incorretos.."            
            
            
    context = RequestContext(request, {'usuario': username, 'state':state } )                  
    return HttpResponse(template.render(context))

def sair(request):    
    logout(request)
    return redirect('/accounts/login')


@login_required()
def normais(request):

    if request.method == 'POST':
        form = PesquisaEstacaoFRM(request.POST)
        if form.is_valid():
            nomeEstac = form.cleaned_data['nomeEstacao']
            estacao = db.Station.objects.filter(Nome__contains = nomeEstac)
            texto     = u'{0}'.format(form.cleaned_data['nomeTexto'])

            if texto.strip() == '':
                texto = estacao[0].Nome
            
            texto = texto.replace('-',' ').replace('.',' ').replace('(',' ').replace(')',' ')
            texto = http.urlquote(texto)

            if estacao:
                return redirect('/grafnormais/{0}/{1}'.format(estacao[0].id, texto.replace(' ', '_')) ) 
    else:
        form = PesquisaEstacaoFRM()    

    colEstacoes = db.Station.objects.filter(tipo='N').values_list('Nome', flat=True)
    saida  = '['
    for i in colEstacoes:
        saida += '\'' +  i + '\','
    saida += ']'
    context = RequestContext(request, { 'estacoes': saida, 'form': form });
    template = loader.get_template('normais.html')   

    return HttpResponse(template.render(context))

@login_required()
def grafnormais(request, station, texto):

    texto = http.urlunquote(texto)
    estacao = {}
    try:
        estacao = db.Station.objects.get(pk=station)
    except:
        return redirect('/normais/')


    grf = NormalGraficos(station, texto).getGrafico()

    template = loader.get_template('grafnormais.html')   
    context = RequestContext(request, { 'estacao': estacao, 'graficos': grf });
    return HttpResponse(template.render(context))

@login_required()
def automaticas(request):

    if request.method == 'POST':

        form = PesquisaAutomaticasFRM(request.POST)
        if form.is_valid():
            nomeEstac = form.cleaned_data['nomeEstacao']
            mes       = form.cleaned_data['mes']
            ano       = form.cleaned_data['ano']
            texto     = u'{0}'.format(form.cleaned_data['nomeTexto'])
            estacao   = db.Station.objects.filter(Nome__contains = nomeEstac)

            if texto.strip() == '':
                texto = estacao[0].Nome

            texto = texto.replace('-',' ').replace('.',' ').replace('(',' ').replace(')',' ')
            texto = http.urlquote(texto)

            if estacao:
                if mes == '99':
                    return redirect(u'/grafautomaticatotal/{0}/{1}'.format(estacao[0].id,texto )) 
                else:
                    return redirect(u'/grafautomatica/{0}/{1}/{2}/{3}/'.format(estacao[0].Codigo, mes, ano,  texto )) 
    else:
        form = PesquisaAutomaticasFRM()    

    colEstacoes = db.Station.objects.filter(tipo='A').values_list('Nome', flat=True)
    saida  = '['
    for i in colEstacoes:
        saida += '\'' +  i + '\','
    saida += ']'
    context = RequestContext(request, { 'estacoes': saida, 'form': form });
    template = loader.get_template('automaticas.html')   

    return HttpResponse(template.render(context))

@login_required()
def grafAutomatica(request, station, ano, mes, texto):

    texto = texto.replace('_', ' ')

    obj = GeraGraficos()
    year = int(ano)
    month  = int(mes)
    if month  == 0:
        tipo = "A"
        month = 1
    else:
        tipo = 'D'

    datadefinida = datetime(year,month,1)
    result = obj.pool( station, datadefinida, tipo, texto)

    context = RequestContext(request, { 'result' : result} )
    template = loader.get_template('graflinha.html')   

    return HttpResponse(template.render(context))



def getautomaticajson(request, station):

    result = json.dumps( { 'dados' :  Medicao().graficos(station) } )

    return HttpResponse(result,content_type='text/javascript')


def dadosAutomatica(request, station):

    result = json.dumps( { 'dados' :  Medicao().graficos(station) } )

    return HttpResponse(result,content_type='text/javascript')

@login_required()
def grafAutomaticaTotal(request, station, texto):

    texto = texto.replace('_', ' ')

    estacao = {}
    try:
        estacao = db.Station.objects.get(pk=station)
    except:
        return redirect('/estacoes/')

    if texto.strip() == '':
        texto = estacao.Nome


    credits = {  'text': 'Powered by: Terravision',
                 'href': 'http://www.terravisiongeo.com.br/'
              }

    context = RequestContext(request, { 'estacao':  estacao, 'credits' : credits, 'texto': texto })
    template = loader.get_template('grafautomaticatotal.html')   

    return HttpResponse(template.render(context))

@login_required()
def mapaestacoes(request):
    context = RequestContext(request)
    template = loader.get_template('mapaestacoes.html')   

    return HttpResponse(template.render(context))

def mapafocoincendio(request):
    context = RequestContext(request)
    template = loader.get_template('mapafocoincendio.html')   

    return HttpResponse(template.render(context))

  
def focoCalor(request, id):

    print id

    reg =  db.FocoItem.objects.get(id=id)

    saida = { 'Temp' :  reg.Temp, 'FireFlag' : reg.FireFlag, 'Data' : reg.foco_FK.dataUTC, 'id' : reg.id }  
    context = RequestContext(request, { 'foco': saida } )

    template = loader.get_template('focoCalor.html')

    return HttpResponse(template.render(context))

weather/proj/normais/templates/automaticas.html
{% extends 'base.html' %} {% load staticfiles %} 

{% block cssformat %}
	<link href="/static/css/typeahead.css" rel="stylesheet">  
{% endblock %}



{% block content %}
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <a href="#" class="show-sidebar">
            <i class="fa fa-bars"></i>
        </a>
        <ol class="breadcrumb pull-left">
            <li><a href="/">Home</a></li>
            <li><a href="/automaticas/">Estações Automáticas</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-cloud"></i>
                    <span>Estações Automáticas</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
            
                <form  method="POST">
                    {% csrf_token %}
                    <div class="row form-group">
                        <div class="col-sm-3">
                            <h4 class="page-header">{{ form.nomeEstacao.label }}</h4>	
                            {{ form.nomeEstacao}}
                        </div>
                        <div class="col-sm-3">
                            <h4 class="page-header">{{ form.mes.label }}</h4>	
                            {{ form.mes}}
                        </div>
                         <div class="col-sm-3">
                            <h4 class="page-header">{{ form.ano.label }}</h4>	
                            {{ form.ano}}
                        </div>
                    </div>
                   <div class="row form-group">
                        <div class="col-sm-3">
                            <h4 class="page-header">{{ form.nomeTexto.label }}</h4>	
                            {{ form.nomeTexto}}
                        </div>
		    </div>
                    <div class="row form-group">
                        <div class="col-sm-3">
                                <button class="btn btn-default" type="submit" ><i class="fa fa-cog"></i> Processar</button>
                        <div>
                    </div>
               </form>
           </div>
        </div>
    </div>
</div>

{% endblock %}



{% block scriptsJava %}
    <script  type="text/javascript" src="/static/js/typeahead/typeahead.jquery.min.js"></script>
	<script>


function Select2Test(){
    $("#el2").select2();
}
$(document).ready(function() {
    // Load script of Select2 and run this
    //LoadSelect2Script(Select2Test);
    //WinMove();

    var substringMatcher = function(strs) {
      return function findMatches(q, cb) {
        var matches, substringRegex;

        // an array that will be populated with substring matches
        matches = [];

        // regex used to determine if a string contains the substring `q`
        substrRegex = new RegExp(q, 'i');

        // iterate through the pool of strings and for any string that
        // contains the substring `q`, add it to the `matches` array
        $.each(strs, function(i, str) {
          if (substrRegex.test(str)) {
            matches.push(str);
          }
        });
    
        cb(matches);
      };
    };
    var states = {{ estacoes|safe }};
    $('#id_nomeEstacao').typeahead({
      hint: true,
      highlight: false,
      minLength: 1
    },
    {
      name: 'states',
      source: substringMatcher(states)
    });
});
</script>
{% endblock %}

weather/proj/normais/templates/focoCalor.html
<br>ID: {{ foco.id }}
<br>Temperatura: {{ foco.Temp }}
<br>Flag: {{ foco.FireFlag }}
<br>Data: {{ foco.Data }}
<br>

weather/proj/normais/templates/login.html
<DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>FIRE-MONITOR   Terravisiongeo</title>
		<meta name="description" content="description">
		<meta name="author" content="Evgeniya">
		<meta name="keyword" content="keywords">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="/static/plugins/bootstrap/bootstrap.css" rel="stylesheet">
		<link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
		<link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
		<link href="/static/css/style_v2.css" rel="stylesheet">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
				<script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
				<script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
<body>
<div class="container-fluid">
	<div id="page-login" class="row">
		<div class="col-xs-12 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
            <form method='POST'>{% csrf_token %}  
                <div class="box">
                    <div class="box-content">
                        <div class="text-center">
                            <h3 class="page-header">FIRE MONITOR - Tela de Acesso</h3>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Usuario</label>
                            <input type="text" class="form-control" name="usuario" />
                        </div>

                        <div class="form-group">
                            <label class="control-label">Senha</label>
                            <input type="password" class="form-control" name="senha" />
                        </div>

                        <div class="text-center">
                            <p>{{ state }}</p>
                        </div>


                        <div class="text-center">
                            <button class="btn btn-primary" type='submit'>Enviar</button>
                        </div>
                    </div>
                </div>
            </form>
		</div>
	</div>
</div>
</body>
</html>

weather/proj/normais/templates/normais.html
{% extends 'base.html' %} {% load staticfiles %} 


{% block cssformat %}
	<link href="/static/css/typeahead.css" rel="stylesheet">  
{% endblock %}



{% block content %}
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <a href="#" class="show-sidebar">
            <i class="fa fa-bars"></i>
        </a>
        <ol class="breadcrumb pull-left">
            <li><a href="/">Home</a></li>
            <li><a href="/normais">Estações Normais</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-cloud"></i>
                    <span>Normais Climatológicas</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
            
            <form  method="POST">
                {% csrf_token %}
                <div class="row form-group">
                    <div class="col-sm-6">
                        <h4 class="page-header">{{ form.nomeEstacao.label }}</h4>	
                        {{ form.nomeEstacao}}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-3">
                        <h4 class="page-header">{{ form.nomeTexto.label }}</h4>	
                        {{ form.nomeTexto}}
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-6">
                        <button class="btn btn-default" type="submit" ><i class="fa fa-cog"></i> Processar</button>                                                 
                    <div>
                </div> 
                </form>
           </div>
        </div>
    </div>
</div>



{% endblock %}a



{% block scriptsJava %}
    <script  type="text/javascript" src="/static/js/typeahead/typeahead.jquery.min.js"></script>
	<script>


function Select2Test(){
    $("#el2").select2();
}

$(document).ready(function() {
    // Load script of Select2 and run this
    //LoadSelect2Script(Select2Test);
    //WinMove();

    var substringMatcher = function(strs) {
      return function findMatches(q, cb) {
        var matches, substringRegex;

        // an array that will be populated with substring matches
        matches = [];

        // regex used to determine if a string contains the substring `q`
        substrRegex = new RegExp(q, 'i');

        // iterate through the pool of strings and for any string that
        // contains the substring `q`, add it to the `matches` array
        $.each(strs, function(i, str) {
          if (substrRegex.test(str)) {
            matches.push(str);
          }
        });
    
        cb(matches);
      };
    };
    var states = {{ estacoes|safe }};
    $('#id_nomeEstacao').typeahead({
      hint: true,
      highlight: false,
      minLength: 1
    },
    {
      name: 'states',
      source: substringMatcher(states)
    });
});
</script>
{% endblock %}a

weather/proj/normais/templates/tela001.html
{% extends 'base.html' %} {% load staticfiles %} 


{% block cssformat %}
	<link href="/static/css/typeahead.css" rel="stylesheet">
{% endblock %}



{% block content %}
<div class="row">
    <div id="breadcrumb" class="col-xs-12">
        <a href="#" class="show-sidebar">
            <i class="fa fa-bars"></i>
        </a>
        <ol class="breadcrumb pull-left">
            <li><a href="index.html">Dashboard</a></li>
            <li><a href="#">Estações</a></li>
        </ol>
        <div id="social" class="pull-right">
            <a href="#"><i class="fa fa-google-plus"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-youtube"></i></a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-6">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-cloud"></i>
                    <span>Estações</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
            
                <form  method="POST">
                    {% csrf_token %}
                    <div class="row form-group">
                        <div class="col-sm-6">
                            <h4 class="page-header">{{ form.nomeEstacao.label }}</h4>	
                            {{ form.nomeEstacao}}
                        </div>
                        <div class="col-sm-6">
                                <button class="btn btn-default" type="submit" ><i class="fa fa-cog"></i> Processar</button>
                        <div>
                    </div>
                </form>
           </div>
        </div>
    </div>
</div>
{% endblock %}a



{% block scriptsJava %}
    <script  type="text/javascript" src="/static/js/typeahead/typeahead.jquery.min.js"></script>
	<script>


function Select2Test(){
    $("#el2").select2();
}

$(document).ready(function() {
    // Load script of Select2 and run this
    LoadSelect2Script(Select2Test);
    WinMove();

    var substringMatcher = function(strs) {
      return function findMatches(q, cb) {
        var matches, substringRegex;

        // an array that will be populated with substring matches
        matches = [];

        // regex used to determine if a string contains the substring `q`
        substrRegex = new RegExp(q, 'i');

        // iterate through the pool of strings and for any string that
        // contains the substring `q`, add it to the `matches` array
        $.each(strs, function(i, str) {
          if (substrRegex.test(str)) {
            matches.push(str);
          }
        });
    
        cb(matches);
      };
    };
    var states = {{ estacoes|safe }};
    $('#id_nomeEstacao').typeahead({
      hint: true,
      highlight: true,
      minLength: 1
    },
    {
      name: 'states',
      source: substringMatcher(states)
    });
});
</script>
{% endblock %}a